/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'niqdev' at '10/24/15 6:49 PM' with Gradle 2.7
 *
 * @author niqdev, @date 10/24/15 6:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
